### ISSUE TITLE
Show system keyboard by default

### ISSUE THREAD

**Issue by sellsky** [burton999dev/CalcNoteHelp#12]
It is really great that CalcNote allows to use the system keyboard as well. It is intended to enter comments I guess. However, as I use this MessagEase keyboard which is quite convenient in both typing and editing, I prefer it over special numeric keypads. Now I have to switch keyboards every time I open CalcNote.
Would you please make a preference whether to show the system keyboard by default? Thanks!

**Comment by burton999dev** [comment]
Thank you for your feature request.
I have a plan to implement it but its date is undecided yet.

**Comment by burton999dev** [comment]
Now all keypad can be disabled.
