### ISSUE TITLE
Can't access currencies on chromebook

### ISSUE THREAD

**Issue by okwme** [burton999dev/CalcNoteHelp#16]
Hello,
First off thank you for making such a great app and making it open source as well <3
I've been using a similar app called numi on my previous mac machine and soulver on my iPhone. Finally I've found your app with similar capabilities for my chromebook with Android support, but the currencies features seems to be embedded in the keyboard which doesn't exist on chromeOS. Do you know how I can access the currency feature? On the previously mentioned apps you would access them like:
```
foo = 25 USD ............................. $25
bar = 100 Euro............................ €100
foobar = 1 BTC............................ 1 BTC
foo + bar + foobar to Eth................. 5.5 ETH
```
I would love to be able to access the currency conversions even if not in this format.

**Comment by burton999dev** [comment]
> First off thank you for making such a great app and making it open source as well

Thank you for using CalcNote.
Unfortunately, CalcNote is not open source.
This repository is for documentation only.

> Do you know how I can access the currency feature?

CalcNote supports currency conversion by the function.
The naming rule for conversion function is simple.

Naming rule is:
[currency prior to conversion] + '_' + [currency after conversion]

For instance:
// 100 EUR(€) -> USD($)
eur_usd(100)
// 1000 JPY(¥) -> EUR(€)
jpy_eur(1000)

Supported currencies are here: 

```
USD
EUR
JPY
GBP
CHF
AUD
CAD
ARS
BGN
BHD
BRL
CLP
CNY
COP
CZK
DKK
HKD
HNL
HRK
HUF
IDR
ILS
INR
JMD
KRW
KWD
LKR
MOP
MXN
MYR
NIO
NOK
NZD
OMR
PAB
PHP
PLN
PYG
QAR
RON
RUB
SAR
SEK
SGD
THB
TRY
TWD
UYU
VND
AED
AFN
ALL
AMD
AOA
AWG
AZN
BAM
BBD
BDT
BIF
BMD
BND
BOB
BSD
BTN
BWP
BYN
BZD
CDF
CRC
CUC
CUP
CVE
DJF
DOP
DZD
EGP
ERN
ETB
FJD
FKP
GEL
GGP
GHS
GIP
GMD
GNF
GTQ
GYD
HTG
IMP
IQD
IRR
ISK
JEP
JOD
KES
KGS
KHR
KMF
KPW
KYD
KZT
LAK
LBP
LRD
LSL
LYD
MAD
MDL
MGA
MKD
MMK
MNT
MRU
MUR
MVR
MWK
MZN
NAD
NGN
NPR
PEN
PGK
PKR
RSD
RWF
SBD
SCR
SDG
SHP
SLL
SOS
SRD
SSP
STD
SVC
SYP
SZL
TJS
TMT
TND
TOP
TTD
TZS
UAH
UGX
UZS
VEF
VUV
WST
XPF
YER
ZAR
ZMW
ZWL
```

Also, supported cryptocurrencies are here: 

```
BTC
ETH
XRP
LTC
DASH
```

**Comment by okwme** [comment]
Beautiful, thank you!
