### ISSUE TITLE
Inline unit conversions

### ISSUE THREAD

**Issue by toddmedema** [burton999dev/CalcNoteHelp#17]
Would love to be able to type things like "5 mi to cm" and see the conversion. Faster than using the conversion keyboard, and provides more context to the rest of the formula!

**Comment by burton999dev** [comment]
CalcNote supports functions for unit conversion and currency conversion.

https://github.com/burton999dev/CalcNoteHelp/issues/16

For instance:
mi_cm(5)

Using these functions allows unit conversion without a conversion keypad.
All conversion functions can be assigned to the button by customizing keypad.

**Comment by toddmedema** [comment]
Oh wow, this is awesome! 5 stars :)
