### ISSUE TITLE
Google play says" Your device isn't compatible with this version"

### ISSUE THREAD

**Issue by chenxiccc** [burton999dev/CalcNoteHelp#21]
Hi:
I'm a calcnote pro users for years.
Today i wiped my phone, and reinstall all apps, only calnote could not be installed.
Google play says" Your device isn't compatible with this version"
But I'm very sure that my device is compatible with your app, for i've installed it on my phone for some times, and it works very well.

**Comment by burton999dev** [comment]
Can you tell me what device and Android version you are using?

**Comment by chenxiccc** [comment]
XiaoMi Mix Fold 2 (Xiaomi 22061218C) and Xiaomi 11 Ultra (Xiaomi M2102K1C)

Android 12 / Miui13

<img width="607" alt="image" src="https://user-images.githubusercontent.com/1096853/189808266-fdf9b935-0d11-4976-b9d3-c4d70a01ab9c.png">

**Comment by chenxiccc** [comment]
When i click "Install on more devices", it show "The app is not available in your country/area". 
My google play location is USA.

**Comment by burton999dev** [comment]
CalcNote Pro is available in all countries supported by Google Play except Russia.
I have checked the app settings and verified that your device is supported.
I have no idea why your device is not able to install app.
Please contact Google Play support team.
https://support.google.com/googleplay/answer/7100415?hl=en

<img width="1214" alt="Advanced settings | CalcNote Pro - Math Calculator 2022-09-13 15-33-26" src="https://user-images.githubusercontent.com/8707881/189830263-898024d8-592a-4108-9463-9e17de105668.png">

![Advanced settings | CalcNote Pro - Math Calculator 2022-09-13 15-34-01](https://user-images.githubusercontent.com/8707881/189830405-3c51e134-e1e1-46ec-90ac-b478e26ee2db.png)

<img width="1206" alt="Device catalog | CalcNote Pro - Math Calculator 2022-09-13 15-36-36" src="https://user-images.githubusercontent.com/8707881/189830346-d739acb5-35d9-402f-a281-cd1cde642807.png">

<img width="1206" alt="Device catalog | CalcNote Pro - Math Calculator 2022-09-13 15-37-28" src="https://user-images.githubusercontent.com/8707881/189830353-7f77586f-b244-40b2-9a5a-40051f8cf290.png">

**Comment by chenxiccc** [comment]
I remembered about 1 month ago, around 16th/17th Aug，I installed CalcNote Pro on the same phone( Xiaomi mix fold 2). It is all ok.
And i found the other phone(Xiaomi 11 Ultra), which CalcNote Pro had already installed, when i search "CalcNote" in Google Play, it could not find CalcNote in the search results list.
Maybe you could check what you have modified in the last month?

**Comment by burton999dev** [comment]
The last update was on May 7, and no changes have been made to the application since then.

<img width="1215" alt="Production | CalcNote Pro - Math Calculator 2022-09-15 16-53-19" src="https://user-images.githubusercontent.com/8707881/190347962-6bef0609-ee47-4485-bebf-e61d11438a42.png">

**Comment by chenxiccc** [comment]
Thanks, maybe I should ask Google for help

**Comment by chenxiccc** [comment]
I contacted Google, and Google replyed that it is not their reason.
Besides I checked all my apps, and found **only** Calcnote shows 'Not available for device'; other apps are all ok, and can be installed properly.
<img width="362" alt="image" src="https://user-images.githubusercontent.com/1096853/190557199-c2fe3a6f-d0dc-4a48-920e-4392709c0512.png">
<img width="361" alt="image" src="https://user-images.githubusercontent.com/1096853/190557472-3a684b02-b5df-45d8-9ad9-3048442bf6ae.png">

**Comment by burton999dev** [comment]
I have sent feedback about this issue to Google Play Console team.
I want to wait for their reply.

**Comment by burton999dev** [comment]
It looks similar to the problem described in this forum.

https://xiaomi.eu/community/threads/22-5-25.65967/page-2

> Netflix App "not available for device" after updating to this version on my Poco F3. Updated from 3 or 4 weeklys back. Widevine shows L1.
>> Try clear data and cache of PlayStore app 
>>> Clearing Playstore app only didn't work, cleared everything google services related and it worked. Thank you!

**Comment by chenxiccc** [comment]
![Screenshot_2022-09-21-14-13-11-416_com android vending](https://user-images.githubusercontent.com/1096853/191430964-84425edc-aa11-4489-899d-baeecb6910da.jpg)
Tried several times but changed nothing.

I cleared google play store cache and data, cleared google play service
cache and data, cleared google service framework cache and data, and I even
removed google account , then redo the actions above, then login again .
But nothing changed.

**Comment by chenxiccc** [comment]
I finally resolved this issue!
I ran a safetynet test, and found "cts profile match" failed.
I installed a magisk module called [safetynet fix](https://github.com/kdrag0n/safetynet-fix),then cleared Google play store/ Google play service / Google service framework cache and data. reboot my phone, and then all come back normally again.
Thanks a lot for you.

**Comment by sc962** [comment]
> I finally resolved this issue! I ran a safetynet test, and found "cts profile match" failed. I installed a magisk module called [safetynet fix](https://github.com/kdrag0n/safetynet-fix),then cleared Google play store/ Google play service / Google service framework cache and data. reboot my phone, and then all come back normally again. Thanks a lot for you.

遇到同样的问题，但是我手机没ROOT，K50，不知道咋弄了

**Comment by chenxiccc** [comment]
> 
> 
> 
> > I finally resolved this issue! I ran a safetynet test, and found "cts profile match" failed. I installed a magisk module called [safetynet fix](https://github.com/kdrag0n/safetynet-fix),then cleared Google play store/ Google play service / Google service framework cache and data. reboot my phone, and then all come back normally again. Thanks a lot for you.
> 
> 遇到同样的问题，但是我手机没ROOT，K50，不知道咋弄了

Have you unlocked your bootloader？
I found if you have unlocked your bootloader , even you have not rooted your phone, it also may impact.

**Comment by burton999dev** [comment]
I'm currently contacting Google support about this problem.
If this is caused by `Automatic Integrity Protection`, I will not activate this feature.
I have already disabled this feature, but it is possible that the device check is enabled for some reason.
