### ISSUE TITLE
Option to add comments

### ISSUE THREAD

**Issue by fadh1l** [burton999dev/CalcNoteHelp#23]
Sometimes I need to add comments but I also don't want the number in it to effect the total value.
eg:
I need to add to lines
#2 + #3  = ans
but here ans is added to the total
so if possible implement a feature so that ans doesn't get added to the output.
eg:
!! #2+#3 where !! will indicate the program not to add the value to total amount.

**Comment by burton999dev** [comment]
In your case, you can use intermediate expression.
Please refer to a help for more details.

http://burton999dev.github.io/CalcNoteHelp/grammar_en.html
